### ISSUE TITLE
Add/update icon for Pipfile and Pipfile.lock

### ISSUE THREAD

**Issue by willsoto** [material-theme/vsc-material-theme-icons#109]
Similar to #91, `Pipefile.lock` shows a Ruby icon. The `Pipfile` itself also doesn't have an icon association. `Pipfile` is from [Pipenv](https://docs.pipenv.org/en/latest/) so it is a Python project.

<img width="124" alt="Screen Shot 2019-09-05 at 7 37 44 PM" src="https://user-images.githubusercontent.com/2791730/64390940-c7b59400-d014-11e9-9465-0f30e0ed0bbd.png">

**Comment by equinusocio** [comment]
Added!
