### ISSUE TITLE
[Java] Icons for different file type (abstract, Class, Interface, Enum)

### ISSUE THREAD

**Issue by HerrDerb** [material-theme/vsc-material-theme-icons#110]
For the `.java` extension, it would be nice if the Icon would indicate the type of `.java` file.
This would include:

- class
- enum
- interface
- abstract class

**Comment by equinusocio** [comment]
Hi @HerrDerb, there are especific filenames for these types? vscode associate the icon only by filename, extension and language. The language is `java` for both these files, same for the extension. The only way to differentiate the icons is by using a specific filenames like other languages. Something like `file.class.java`

**Comment by HerrDerb** [comment]
Hi @equinusocio so this is a resctricion of VSC then. A shame... I'll close the issue
