### ISSUE TITLE
Add icon for Nunjucks

### ISSUE THREAD

**Issue by ccalvarez** [material-theme/vsc-material-theme-icons#111]
Hi, I'm editing .njk files.

Some information about the file extension:  https://github.com/mozilla/nunjucks/issues/398

I'm watching a course and the instructor has this:

![image](https://user-images.githubusercontent.com/2665104/68517729-5bdaec00-024e-11ea-941d-e8e0197ffb09.png)

Thank you!

**Comment by equinusocio** [comment]
Added!
