### ISSUE TITLE
Add file icon for Jupyter/Ipython

### ISSUE THREAD

**Issue by vivekpayasi** [material-theme/vsc-material-theme-icons#113]
Can we have file icons for Jupyter Notebooks with `.ipynb` file extension?

**Comment by equinusocio** [comment]
Hi @vivekpayasi, can you suggest the logo we should use? Any link to official resources are welcome.

**Comment by vivekpayasi** [comment]
Sure.

The Jupyter Brand guide is here: https://github.com/jupyter/design
In this repo, there is a folder named `logos` where you can find the logos of various sizes and backgrounds.

**Comment by equinusocio** [comment]
Thank you!

**Comment by equinusocio** [comment]
Added!

**Comment by vivekpayasi** [comment]
Thanks :)
