### ISSUE TITLE
Pop-up everytime I open vscode with Remote-WSL

### ISSUE THREAD

**Issue by phillpeters** [material-theme/vsc-material-theme-icons#114]
I am connecting vscode to WSL using the Remote-WSL extension.  Every time I open a new instance of vscode I get a pop-up saying "Thank you for using Material Theme Icons! Install also the Material Theme for a more immersive experience."  I can then select either "Sure!" or "Nope".  If I select "Sure!" I am taken to the Material Theme extension page which recognizes that is indeed already installed.

When I connected to WSL, the Material Theme Icons was disabled locally and enabled on the remote.  This was not the case with the Material Theme extension.  Is this why Material Themes Icon is not recognizing that Material Theme is installed?  Is there a way I can disable this notification?

**Comment by vivekpayasi** [comment]
I'm experiencing the same issue. 

I have not installed the Material Theme though. Only Material Theme Icons does not add any settings, hence I couldn't find a way to turn these notifications off.

It would be great to have a setting that can toggle the notifications for Material Theme Icons.

**Comment by LasaleFamine** [comment]
Hi guys and thanks for reporting this one.

Seems like our `persistent-settings` are not working within the Remote-WSL or at least they are created every time the WSL is opened, this is why we are not able to [check if it's a first installation or not](https://github.com/material-theme/vsc-material-theme-icons/blob/master/src/extension.ts#L14). This is something we need to investigate, maybe we can use some new APIs to detect this situation.

We are in the middle of rewriting the Material Theme, so I think we need few days to work on this one. Thank you for your comprehension.

**Comment by phillpeters** [comment]
No problem @LasaleFamine.  Glad to be of assistance.

**Comment by OverMighty** [comment]
I'm running VS Code on Linux and I also get the notification every time I launch VS Code, even though I have the "Community Material Theme" extension (`equinusocio.vsc-community-material-theme`) installed.

**Comment by equinusocio** [comment]
@LasaleFamine Material Theme Icons are now set as extensionPack and downloaded automatically with the main extension. We should edit/remove such notification or check if icons are already installed.

**Comment by equinusocio** [comment]
This should be fixed with the latest release
