### ISSUE TITLE
Add icon for vs code rest client

### ISSUE THREAD

**Issue by shingravirei** [material-theme/vsc-material-theme-icons#146]
Hello, 
there's no icon for .rest files

**Comment by equinusocio** [comment]
Which icon you suggest for these files?

**Comment by shingravirei** [comment]
> Which icon you suggest for these files?

It could be like this

![rest](https://user-images.githubusercontent.com/42350757/75188754-77013700-572b-11ea-8302-ca0ed1ae2b3f.jpg)
