### ISSUE TITLE
DVC icon support

### ISSUE THREAD

**Issue by iakremnev** [material-theme/vsc-material-theme-icons#150]
Add an icon for `.dvc` files.
Sample icon: https://i.imgur.com/YGWWPii.png

Original logo can be obtained from dvc-public aws s3 bucket following command
```dvc get https://github.com/iterative/dataset-registry images/dvc-logo-outlines.png```
(see https://github.com/iterative)
Linked [issue](https://github.com/vscode-icons/vscode-icons/issues/2467) in vscode-icons repo

**Comment by equinusocio** [comment]
Is there a vector format?

**Comment by iakremnev** [comment]
Here is what I was able to extract from dvc.org: https://gist.github.com/iakremnev/db3f9d5d580d53f4cf34f38773682b4a
