### ISSUE TITLE
Add "display explorer arrow" option

### ISSUE THREAD

**Issue by leokun** [material-theme/vsc-material-theme-icons#151]
Hello there,

By any chance, is it possible to add an option to show/hide explorer arrows near the folder. I like when I see them and I like your work so, pretty please ? :smiling_face_with_three_hearts: 

Thanks a lot for your time.
Regards,
Leo

**Comment by francis-zhao** [comment]
I think the icon of your product is the best-looking in vscode, but I personally think that it looks too strange without a navigation arrow, and the display of multi-layer folders is not intuitive. Could you consider this proposal and give us a choice of options to customize whether to display the navigation arrow?

**Comment by equinusocio** [comment]
Hello, unfortunately we can't, it's not a choice. VSCode api doesn't provide api for that, to enable/disable the arrows you have to change the theme file itself, it's not something we can handle with user preferences like accents. We'll investigate this but at the moment we don't have a solution, they can be enabled or disabled by default for everyone.

**Comment by francis-zhao** [comment]
> Hello, unfortunately we can't, it's not a choice. VSCode api doesn't provide api for that, to enable/disable the arrows you have to change the theme file itself, it's not something we can handle with user preferences like accents. We'll investigate this but at the moment we don't have a solution, they can be enabled or disabled by default for everyone.

Thanks anyway.

Hey guys, to those who have this need, you can modify this file on Windows by yourself:



```batch
REM VSCode:

%USERPROFILE%\.vscode\extensions\equinusocio.vsc-material-theme-icons-*\out\variants\Material-Theme-Icons-*.json

REM VSCode Insiders:

%USERPROFILE%\.vscode-insiders\extensions\equinusocio.vsc-material-theme-icons-*\out\variants\Material-Theme-Icons-*.json
```

Material-Theme-Icons-*.json

```jsonc
// before
{"hidesExplorerArrows":true}

// after
{"hidesExplorerArrows":false}
```

**Comment by equinusocio** [comment]
> > Hello, unfortunately we can't, it's not a choice. VSCode api doesn't provide api for that, to enable/disable the arrows you have to change the theme file itself, it's not something we can handle with user preferences like accents. We'll investigate this but at the moment we don't have a solution, they can be enabled or disabled by default for everyone.
> 
> Thanks anyway.
> 
> Hey guys, to those who have this need, you can modify the config file at the following path:
> 
> ```
> # Windows
> %USERPROFILE%\.vscode[-insiders]\extensions\equinusocio.vsc-material-theme-icons-<version>\out\variants
> 
> # Linux
> $HOME/.vscode[-insiders]/extensions/equinusocio.vsc-material-theme-icons-<version>/out/variants
> ```
> 
> or simply run this cmdlet in `Windows PowerShell`/`PowerShell Core`:
> 
> ```powershell
> # Windows
> explorer (Get-ChildItem $HOME\.vscode*\extensions\equinusocio.vsc-material-theme-icons-*\out\variants)[-1]
> ```
> 
> You may find some `Material-Theme-Icons-*.json` files, just open the one you use, modify the following content and save:
> 
> ```js
> // before
> {"hidesExplorerArrows":true}
> 
> // after
> {"hidesExplorerArrows":false}
> ```

Plase note that you will lose this on every extension update.
