### ISSUE TITLE
html files showing no icons.

### ISSUE THREAD

**Issue by jvmMachado** [material-theme/vsc-material-theme-icons#153]
After the last update .html files stopped showing the propper html icon. They just do so if you use .htm instead of .html.

I solved that on my own setting by adding the following to my settings.json:

"material-icon-theme.files.associations": {
    "*.html": "html"
  }

**Comment by equinusocio** [comment]
We're able to reproduce this on Vscode 1.45.1

![Screenshot 2020-05-20 at 21 12 07](https://user-images.githubusercontent.com/10454741/82487374-90bdda80-9ade-11ea-8c9f-0c29082a2d1c.png)

Please check if're using some extension related to html files and check if the language id is correct when opening the file:

![Screenshot 2020-05-20 at 21 12 54](https://user-images.githubusercontent.com/10454741/82487518-bc40c500-9ade-11ea-92f7-a20a82c51857.png)
:
