### ISSUE TITLE
Add support for open source extension marketplace (Coder)

### ISSUE THREAD

**Issue by CoreyVidal** [material-theme/vsc-material-theme-icons#154]
I've switched from using Visual Studio Code as a Windows desktop application to using it in my browser through Docker. (Check out "coder": https://github.com/cdr/code-server)

The main "Material Theme" is a viable extension and already shows up, but the other 2 extensions you offer are not (Community and Icons).

Would love to get Icons in there, to make my workspace complete. 🙂

You can see how to make Material Theme Icons scrapable here: https://github.com/cdr/code-server/blob/master/doc/FAQ.md#whats-the-deal-with-extensions

**Comment by equinusocio** [comment]
> To request an extension for the code-server marketplace, please open a new issue and select the Extension request template.
