### ISSUE TITLE
Doesn't seem to map file extensions with custom file associations setting

### ISSUE THREAD

**Issue by ux-engineer** [material-theme/vsc-material-theme-icons#161]
In my project's `.vscode/setting.json`

```
  "files.associations": {
    ".env.analyze": "dotenv",
  },
```

I'm seeing only the default file icon (blue borderlines of a file)... Should this work out of the box or is this supported?

**Comment by equinusocio** [comment]
Can you check the latest version in minutes?

**Comment by ux-engineer** [comment]
@equinusocio I'm not on VS Code Insider but regular...do I need to wait for the upgrades?

**Comment by equinusocio** [comment]
Open the extensions panel and check if the extension is updated, you should get 1.2.2 automatically.
