### ISSUE TITLE
nginx icon folder support

### ISSUE THREAD

**Issue by logustra** [material-theme/vsc-material-theme-icons#164]
here's the SVG icon
[nginx.svg.zip](https://github.com/material-theme/vsc-material-theme-icons/files/5280523/nginx.svg.zip)

you can find out the original logo here
https://www.nginx.com/wp-content/uploads/2020/05/NGINX-product-icon.svg

**Comment by equinusocio** [comment]
Hello, what's the name/pattern of the folder?

**Comment by logustra** [comment]
like this
```
nginx/
├── nginx.development.conf
└── nginx.production.conf
```
