### ISSUE TITLE
Unable to read file

### ISSUE THREAD

**Issue by pauloedurezende** [material-theme/vsc-material-theme-icons#168]
Hey :wave: 

After I updated the extension to its latest version (1.2.1) I started to notice that some icons were not being loaded, so I performed a clean installation of the extension and now I'm getting this error:

![Screenshot from 2020-12-21 09-26-27](https://user-images.githubusercontent.com/38743434/102777367-34ba7d80-436f-11eb-928f-f1f83977b44f.png)

I installed the previous version (1.2.0) and everything is working as it should...

**Comment by saitolume** [comment]
I faced the same error.

**Comment by equinusocio** [comment]
We relased a 1.2.2. Please check it out.

**Comment by pauloedurezende** [comment]
Working properly, no problems so far... 🎉
