### ISSUE TITLE
Pink Dot Icon on File

### ISSUE THREAD

**Issue by NuclearPowerNerd** [material-theme/vsc-material-theme-icons#169]
Hello,

I was wondering, what does the pink dot signify in the file structure? 
I can't find an explanation anywhere.

![image](https://user-images.githubusercontent.com/58567518/102794069-cda1c680-4378-11eb-84db-d9e49fe18e9d.png)

**Comment by equinusocio** [comment]
The pink bullet is indicating that the folder is a root folder, it appears on every root folder when you add multiple root directories to the current project.

**Comment by NuclearPowerNerd** [comment]
Thank you!
