### ISSUE TITLE
tests icon file support

### ISSUE THREAD

**Issue by sandersonsoares** [material-theme/vsc-material-theme-icons#170]
it would be interesting to use specific icons for test files.

It could be used in files with nomenclatures such as:

* .spec. *
* .test. *

Example:

name-component.test.jsx

Attached is an SVG icon that could be used.

for js:
https://github.com/PKief/vscode-material-icon-theme/blob/master/icons/test-js.svg

for jsx:
https://github.com/PKief/vscode-material-icon-theme/blob/master/icons/test-jsx.svg

for ts:
https://github.com/PKief/vscode-material-icon-theme/blob/master/icons/test-ts.svg

Or you could use one of them for all test files regardless of language.

**Comment by equinusocio** [comment]
At the moment VSCode allows only "exact file name" and `file extension` matches. This means that we can't use glob to target files that include `.test`  and `.spec`. We would have to define all the possible combinations between extensions and `.spec/.test`.

**Comment by abelfubu** [comment]
It would be great to have cypress folder support! thanks for the amazing theme!

**Comment by equinusocio** [comment]
@abelfubu Please open a new issue with the request
