### ISSUE TITLE
Support new file nesting feature

### ISSUE THREAD

**Issue by acidoxee** [material-theme/vsc-material-theme-icons#191]
Since the January release, vscode [has an experimental feature to support file nesting](https://code.visualstudio.com/updates/v1_64#_explorer-file-nesting), which is a way to scope some related files together.

By default, nested files are expanded and work great with this icon theme (after all, it's just a changed level of indentation): 
| Unfolded parent at startup | Unfolded parent at startup (Minimal theme) |
| :---: | :---: |
| ![image](https://user-images.githubusercontent.com/23697296/157811911-08c9b687-5fb5-4a43-8bb2-d15ef56e1d59.png) | ![image](https://user-images.githubusercontent.com/23697296/157812696-53e3bb14-377e-492b-ba8d-560b182bc464.png) |

Problem is, since Material Theme Icons do not display folding indicators, as soon as you fold everything back (with the "Collapse Folders in Explorer" button for instance, which I use extensively each time I'm done working with a given set of files), it seems impossible right now to expand back the files that contain such nested children (apart from using the keyboard), as there are no visual toggles to do so, and clicking on the file does not re-expand its children:
| Folded parent | Folded parent (Minimal theme) |
| :---: | :---: |
| ![image](https://user-images.githubusercontent.com/23697296/157812377-bbe0b6de-f8be-4ab2-8917-daf440c3df00.png) | ![image](https://user-images.githubusercontent.com/23697296/157813003-55878b5a-b7f7-4d02-8ed7-9cab77cbd887.png) |

It is also quite confusing, visually speaking, because we're not able to know at a glance whether a file has children nested files or not, as there are no visual cues whatsoever.

I'm wondering what could be done to fix both those problems?

**Comment by equinusocio** [comment]
Hello, thanks for reporting this issue. Unfortunately this depends on the VSC API. We don't have any way to force arrow indicators only for nested files.

They are working on this, check here:
https://github.com/microsoft/vscode/issues/6328#issuecomment-1062025331

**Comment by acidoxee** [comment]
Thanks Mattia, will check it out and wait for something to happen over there!

**Comment by babakfp** [comment]
@acidoxee

This is kinda related, see this feature request and if it interests you, you can ask the Contributor to maybe add it🤷‍♂️
https://github.com/microsoft/vscode/issues/141428#issuecomment-1047233297

I disabled file nesting because it had issues so, probably it will be better next year 😂🥲

**Comment by acidoxee** [comment]
Thanks @babakfp, I'll take a look.

If there is nothing more to do on this package's side to make file nesting work and display arrows just for files, I guess we can close this issue and call it a day? Your call @equinusocio, because I'm not sure if you'll have some small settings to add to the extension so that it works "magically" for everyone who installs it, or if it will always be the user's responsibility anyway to tweak the settings manually.
