### ISSUE TITLE
[Icon Request] - NGRX icons

### ISSUE THREAD

**Issue by alex-aghamyan** [material-theme/vsc-material-theme-icons#195]
NGRX icons for reducers, state, actions, effects files would be very nice.
`*.actions.ts`
`*.*reducer.ts` for `rootReducer.ts` `feature.reducer.ts` `root.reducer.ts` etc..
`*.state.ts`
`*.effects.ts`
`*.selectors.ts`
Also for the related folders too: **store, state, actions, reducers, effects, selectors**.

Possibly can be used different color iterations of image below.

![28226848-9903db36-68a5-11e7-9056-f37d8a77067e](https://user-images.githubusercontent.com/71812898/165986388-a205606c-2bc8-48e9-944b-2020ebba9587.png)

**Comment by equinusocio** [comment]
Without a language id is not possible to add icon for those files since every file with that names (which are generic) will use the icon, even if they are not related to Angular.

**Comment by alex-aghamyan** [comment]
Ok, another question.
How do you think is it possible to make these icons optional, so user can choose them by himself?

**Comment by equinusocio** [comment]
Atm is not possible. We rely on VSC API, and there is no way for users to customize icon themes using the "standard" way.

The only possible hack is to manually edit the installed extension (the theme JSON file) inside the Extensions directory, BUT you'll lose the editing every extension update.

**Comment by alex-aghamyan** [comment]
Closing due to the inability to resolve this feature.
