### ISSUE TITLE
Add gRPC folder icon

### ISSUE THREAD

**Issue by ehduardu** [material-theme/vsc-material-theme-icons#196]
Icon example:

![7802525](https://user-images.githubusercontent.com/32852890/166584534-3fe66ea6-34b9-4d4f-aff3-1c485a849365.png)

**Comment by equinusocio** [comment]
Please provide file extensions and/or language id used

**Comment by ehduardu** [comment]
It's for folders that contains gRPC informations, like `.proto` files

**Comment by equinusocio** [comment]
So the icon should be applied for folders called GRPC only?

**Comment by ehduardu** [comment]
yep

**Comment by equinusocio** [comment]
The icon is being assigned to folders with name `GRPC` and `grpc
`
