### ISSUE TITLE
Change docker-compose icon

### ISSUE THREAD

**Issue by julianoboese** [material-theme/vsc-material-theme-icons#203]
Hey, people!

Could you change the icon for a `docker-compose.yml` file from the ordinary `.yml` icon

![image](https://user-images.githubusercontent.com/93009900/170500454-09d187be-3f60-49e5-9cee-0482eee4578d.png)

to the Docker icon?

![image](https://user-images.githubusercontent.com/93009900/170500895-9390b729-b9f8-4c26-87a6-b45f2b8dd461.png)

Thanks!

**Comment by equinusocio** [comment]
Fixed in next release
