### ISSUE TITLE
Add icon for Apex / Salesforce

### ISSUE THREAD

**Issue by freddysilber** [material-theme/vsc-material-theme-icons#206]
Would it be possible to add an icon for Apex / Salesforce files? currently they show up with a `TEX` icon but some other themes have the salesforce cloud logo for `.apex` files. 

If this is something worth making, I'd be happy to issue a PR for this 😁

**Comment by equinusocio** [comment]
Hello, can you provide the svg logo to use and all the extensions and language names to associate with it? Thanks.

**Comment by freddysilber** [comment]
Heres a link to the image: https://cdn.icon-icons.com/icons2/2699/PNG/512/salesforce_logo_icon_170764.png

![salesforce_cloud](https://user-images.githubusercontent.com/38798049/186698327-4f97b51b-0fea-421a-98cf-8758d30cb2cb.png)

The file extensions would be:
- `.cls`
- `.trigger`

**Comment by equinusocio** [comment]
Any language ids associated the language? You can see it between brackets when you run the change language mode command.

**Comment by freddysilber** [comment]
(apex) and (apex-anon)
