### ISSUE TITLE
add wakatime icon

### ISSUE THREAD

**Issue by chraebsli** [material-theme/vsc-material-theme-icons#211]
add icon for wakatime (.wakatime-project)

**Comment by equinusocio** [comment]
Hello, please provide:
- svg logo
- all the file extensions 
- associated language ids

**Comment by chraebsli** [comment]
@equinusocio 
SVG logo: https://wakatime.com/safari-pinned-tab.svg
File Extensions: .wakatime-project

**Comment by equinusocio** [comment]
Is there any language-id associated? You can find it in the bottom right corner when opening the file.

**Comment by chraebsli** [comment]
I think its just plan text
