### ISSUE TITLE
Extension commands not showing on the Command Palette or settings.json

### ISSUE THREAD

**Issue by CarterSnich** [material-theme/vsc-material-theme-icons#222]
None of your commands shows up on the Command Palette or in the `settings.json` file. I don't know if it is because I am using [VSCodium](https://vscodium.com/). I just want to show the directory arrows on the Explorer.

Command Palette
![Command Palette](https://user-images.githubusercontent.com/52433531/230541989-5bae21f7-9639-4fc4-9ca9-c84b4892acfa.png)

`settings.json`
![settings.json](https://user-images.githubusercontent.com/52433531/230542066-a57149e1-0479-4841-ab94-9eb54b6b9622.png)

**Comment by equinusocio** [comment]
We don't support vscodium. Check if there is the build folder inside Material Theme extension directory. That folder is required  for any commands or customizations.
