### ISSUE TITLE
Custom icons with file associations

### ISSUE THREAD

**Issue by fabiopicolijr** [material-theme/vsc-material-theme-icons#224]
I would like to suggest adding the ability to customize icons like the "Material Icon Theme" functionality.

e.g.
"vsc-material-theme-icons.files.associations": {
    "*.ts": "typescript",
    "**.json": "json",
    "fileName.ts": "angular"
}

**Comment by equinusocio** [comment]
Atm there are no plan to add this functionality. Our original icons are made to fullfill the material theme experience and colors. We want to maintain this quality standard and work with feature request for new icons.
