### ISSUE TITLE
Add icon support for the Zig programming language

### ISSUE THREAD

**Issue by devraymondsh** [material-theme/vsc-material-theme-icons#225]
When using the icon theme, it can't detect zig files. The default icon pack for vs code suppports it tho but not this icon pack.

**Comment by equinusocio** [comment]
Hello, please provide:
- file extensions associated
- language id
- vector logo or url to it

Thanks.

**Comment by devraymondsh** [comment]
There are `.zig` and `.zig.zon` files. The `.zig` extension contains code for the Zig programming language. You can think of `.zig.zon` as something like JSON, I don't think there's an icon for it, I'd say use the same `.zig` icon for that.

I didn't find an id for the Zig programming language at https://code.visualstudio.com/docs/languages/identifiers. The language is configured by the [`Zig Language`](https://marketplace.visualstudio.com/items?itemName=ziglang.vscode-zig) extension.

The vector logo I found is located at https://www.vectorlogo.zone/logos/ziglang/ziglang-icon.svg.

Thanks for considering this issue.

**Comment by equinusocio** [comment]
To get the language id (for each file extensions) install the extension and run the command "change language mode" you will see the language id between (), beside the language name. Check if is the same for both file extensions.

**Comment by zraineri** [comment]
They are both (zig)

**Comment by equinusocio** [comment]
Releasing right now
