### ISSUE TITLE
Add icons to differentiate test files

### ISSUE THREAD

**Issue by rtanguyen** [material-theme/vsc-material-theme-icons#226]
Would love it if there was a separate icon for test files! Especially for those super long file names 

File extensions: `.spec.ts` `.spec.tsx` etc
SVG: https://github.com/PKief/vscode-material-icon-theme/blob/main/icons/test-js.svg
Or a red react icon similar to VSCode's Seti theme

**Comment by equinusocio** [comment]
Is `.spec` a standard? we can assign icons to a glob pattern so we would specify every possible file name (.test, .spec, .fixture... ecc), for each file extension.
