### ISSUE TITLE
feature request: add icons for config files, vite / styllint ...

### ISSUE THREAD

**Issue by issam-seghir** [material-theme/vsc-material-theme-icons#228]
it would be great if you could include an icon for config files like stylelint / postcss / vite.

**Comment by equinusocio** [comment]
Hello, we already support stylelint and postcss configs.

**Comment by issam-seghir** [comment]
> Hello, we already support stylelint and postcss configs.

![image](https://github.com/material-theme/vsc-material-theme-icons/assets/74573675/fc83a42e-64c5-4661-9bc3-f0d0c8a66def)

i use the last version of the extension

**Comment by equinusocio** [comment]
Oh, ok, is a matter of extensions. We'll add more extensions.
