### ISSUE TITLE
Add new ESLint "flat" config file (`eslint.config.js`) in the list 

### ISSUE THREAD

**Issue by acidoxee** [material-theme/vsc-material-theme-icons#231]
The [new `eslint.config.js` file](https://eslint.org/docs/latest/use/configure/configuration-files-new) should be added to the current list:

https://github.com/material-theme/vsc-material-theme-icons/blob/f6eb086336f71f5532303c20ff840cc17e230a2b/src/icons/partials/fileNames.js#L108-L115

Thanks!

**Comment by equinusocio** [comment]
Hello, we already support all those file extensions/names.
![CleanShot 2023-10-09 at 11 40 52](https://github.com/material-theme/vsc-material-theme-icons/assets/10454741/61a0b222-4dc4-401b-b28d-6fc7eb88db95)

**Comment by equinusocio** [comment]
Release on the way
