### ISSUE TITLE
Add Kivy Design Language (.kv) Icons

### ISSUE THREAD

**Issue by simplePCBuilding** [material-theme/vsc-material-theme-icons#235]
Hello

Does anybody have any plans to add the kivy design language icons?

Currently, these files are shown as plain text files.

**Comment by equinusocio** [comment]
Hello, can you provide the langage id, filex estensions and the SVG logo?

**Comment by simplePCBuilding** [comment]
Hello

I will be uploading the svg very soon. The extensions of the file are .kv and there doesn't appear to be a language code for it. 

[SVG](https://static.janishutz.com/kivy.svg)

**Comment by simplePCBuilding** [comment]
Update: Uploaded

**Comment by equinusocio** [comment]
Release on the way
