### ISSUE TITLE
Add `biomejs` icon support

### ISSUE THREAD

**Issue by caiulucas** [material-theme/vsc-material-theme-icons#237]
[Biomejs](https://biomejs.dev/) is a new formatter and linter for javascript ecosystem made in rust.

Here is the [npm page](https://www.npmjs.com/package/@biomejs/biome) of the package.

By following the [docs](https://biomejs.dev/reference/configuration/), the only file that should have an icon is the `biome.json`.

And here is the [svg](https://biomejs.dev/img/favicon.svg) from the official website.

Thanks!
![favicon](https://github.com/material-theme/vsc-material-theme-icons/assets/46914545/643a97b9-358d-443b-9d70-b31d42eb61c3)
 ^^

**Comment by equinusocio** [comment]
Can you confirm there isn't any specific language id associated with the file?

**Comment by caiulucas** [comment]
> Can you confirm there isn't any specific language id associated with the file?

it is json

**Comment by equinusocio** [comment]
They have changed the logo. Added the new one and new release will go live in minutes
