### ISSUE TITLE
Add more Yarn icon matches

### ISSUE THREAD

**Issue by acidoxee** [material-theme/vsc-material-theme-icons#239]
Yarn v4 has a few new dedicated files for [config, dependency overrides](https://yarnpkg.com/configuration/yarnrc) and [constraints](https://yarnpkg.com/features/constraints):

- `.yarnrc.yml`
- `yarn.config.cjs`

Would it be possible to add those files to match the existing `_file_yarn` icon? 🙏

**Comment by equinusocio** [comment]
Didn't know yarn still a thing.

**Comment by acidoxee** [comment]
> What are the valid file extensions for `yarn.config` file?

For now the docs only mention `yarn.config.cjs` exactly. This also seems confirmed by [this piece of code](https://github.com/yarnpkg/berry/blob/943a9f08936ee3f44441c2cc86351a9da6561fa8/packages/yarnpkg-core/sources/Project.ts#L722).

**Comment by equinusocio** [comment]
So there is no support for .yarnrc.json?

**Comment by acidoxee** [comment]
Not that I know of, no. I don't see it mentioned anywhere in the docs (the new ones for v4 at least). Although I guess you could still add it to the mapping to be safe? But I'm quite positive it's not supported.
