### ISSUE TITLE
Add Bun icon

### ISSUE THREAD

**Issue by Ram-Amoncar** [material-theme/vsc-material-theme-icons#241]
Hi, I would like to request the addition of the Bun icon for files like `bun.lockb`.
The SVG logo/icon are available here: https://bun.sh/press-kit 

If you could consider this, that would be great! Thanks! 🥖

**Comment by equinusocio** [comment]
Can you list all the file extensions and languages associated to bun?

**Comment by Ram-Amoncar** [comment]
- `.bunfig.toml` 
- `bunfig.toml`
- `*.lockb`

I am not sure if there are more.
