### ISSUE TITLE
Opinion(?): The new gradient folder icon should be reverted

### ISSUE THREAD

**Issue by Ned-el-ch** [material-theme/vsc-material-theme-icons#250]
As the title says, the new "gradient" folder icon should from v3.8.0 be reverted IMO. Its style doesn't fit the aesthetic of the theme. I don't know where else to submit feedback so posting here, feel free to remove

**Comment by equinusocio** [comment]
Hello, to submit feedback and start a discussion with other people use the [Discussions](https://github.com/material-theme/vsc-material-theme-icons/discussions) page. Issues are for bugs.

Material Theme and Icons have been open-source for ~9 years, we never asked our over 7 million users to support us, and we didn't get a single code contribution over this time. Now we are going to change a lot of stuff. If you don't like the new style changes, you are free to switch to another extension or become an active contributor to improve the extension and offer more possibilities.

Said that, we are going to add gradients to every icon and update the overall style of Material Theme
