### ISSUE TITLE
when update new version,icon theme is not work

### ISSUE THREAD

**Issue by badspider7** [material-theme/vsc-material-theme-icons#255]
Hello,i hava some question in this vscode plugin which i very loved.
Material Theme Icons — Free version v3.8.5.
I try to relaunch vscode plugin system and vscode, it is not work.
My machine is window 11.

![image](https://github.com/user-attachments/assets/3e6fc5ed-caae-42aa-8987-77317ea5d648)

**Comment by equinusocio** [comment]
Yep sorry for the inconvenience, the fix is on the way.

**Comment by equinusocio** [comment]
Released an extra fix to fix missing variant colors
