### ISSUE TITLE
Add icon for .spec.ts and .spec.js files

### ISSUE THREAD

**Issue by TheDutchCoder** [material-theme/vsc-material-theme-icons#261]
### Description

It would be great to have support for `.spec.ts` and `.spec.js` files, which are defaults for test files in front-end development.

**Comment by equinusocio** [comment]
Hello, at the moment both files use a dedicated flsk icon. What do you mean with "add support"?

**Comment by equinusocio** [comment]
> Ah I see, this is regarding the Palenight version. I'm assuming that's not your work but someone's fork?

Yes, there are many license-violating republish of the original Material Theme (this one). If you want to use the original and up-to-date theme and icons, consider to use Material Theme and Material Theme icons by Equinusocio.
